version: '3'
services:
  main:
    build: ./main
    ports:
      - '8081:8080'

  secondary-instance-1:
    build: ./secondary
    ports:
      - '8082:8080'

  secondary-instance-2:
    build: ./secondary
    ports:
      - '8083:8080'
